# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ribscan.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 480, 310))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(165, 190, 150, 34))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 60, 18))
        self.label_4.setObjectName("label_4")
        self.progressBarEmail = QtWidgets.QProgressBar(self.tab)
        self.progressBarEmail.setGeometry(QtCore.QRect(90, 110, 370, 24))
        self.progressBarEmail.setProperty("value", 0)
        self.progressBarEmail.setTextVisible(False)
        self.progressBarEmail.setObjectName("progressBarEmail")
        self.progressBarScan = QtWidgets.QProgressBar(self.tab)
        self.progressBarScan.setGeometry(QtCore.QRect(90, 50, 370, 24))
        self.progressBarScan.setProperty("value", 0)
        self.progressBarScan.setTextVisible(False)
        self.progressBarScan.setObjectName("progressBarScan")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 57, 18))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_save = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_save.setEnabled(False)
        self.pushButton_save.setGeometry(QtCore.QRect(317, 230, 150, 34))
        self.pushButton_save.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_save.setObjectName("pushButton_save")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(10, 30, 126, 18))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 146, 18))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 176, 18))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_naps2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_naps2.setGeometry(QtCore.QRect(10, 110, 420, 24))
        self.lineEdit_naps2.setReadOnly(True)
        self.lineEdit_naps2.setObjectName("lineEdit_naps2")
        self.lineEdit_thunderbird = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_thunderbird.setGeometry(QtCore.QRect(10, 170, 420, 24))
        self.lineEdit_thunderbird.setReadOnly(True)
        self.lineEdit_thunderbird.setObjectName("lineEdit_thunderbird")
        self.toolButton_naps2 = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_naps2.setGeometry(QtCore.QRect(440, 110, 28, 24))
        self.toolButton_naps2.setObjectName("toolButton_naps2")
        self.toolButton_thunderbird = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_thunderbird.setGeometry(QtCore.QRect(440, 170, 28, 24))
        self.toolButton_thunderbird.setObjectName("toolButton_thunderbird")
        self.lineEdit_pdf = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_pdf.setGeometry(QtCore.QRect(10, 50, 420, 24))
        self.lineEdit_pdf.setText("")
        self.lineEdit_pdf.setReadOnly(True)
        self.lineEdit_pdf.setObjectName("lineEdit_pdf")
        self.toolButton_pdf = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_pdf.setGeometry(QtCore.QRect(440, 50, 28, 24))
        self.toolButton_pdf.setObjectName("toolButton_pdf")
        self.pushButton_save.raise_()
        self.lineEdit_pdf.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 350, 481, 91))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuEdit.addAction(self.actionSettings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ribscan"))
        self.pushButton.setText(_translate("MainWindow", "Scan and Email PDF"))
        self.label_4.setText(_translate("MainWindow", "Scanning:"))
        self.label_5.setText(_translate("MainWindow", "Emailing:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Scan && Email PDF"))
        self.pushButton_save.setText(_translate("MainWindow", "Save Configuration"))
        self.label.setText(_translate("MainWindow", "Default PDF Location"))
        self.label_2.setText(_translate("MainWindow", "NAPS2 Console Location"))
        self.label_3.setText(_translate("MainWindow", "Mozilla Thunderbird Location"))
        self.toolButton_naps2.setText(_translate("MainWindow", "..."))
        self.toolButton_thunderbird.setText(_translate("MainWindow", "..."))
        self.toolButton_pdf.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Settings"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionExit.setText(_translate("MainWindow", "&Exit..."))
        self.actionExit.setToolTip(_translate("MainWindow", "Quit application"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "&About..."))
        self.actionAbout.setToolTip(_translate("MainWindow", "About Ribscan"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionSettings.setText(_translate("MainWindow", "Settings..."))
        self.actionSettings.setToolTip(_translate("MainWindow", "Change settings"))
        self.actionSettings.setShortcut(_translate("MainWindow", "Ctrl+E"))

